### ISSUE TITLE
Incompatible with Leaflet 1.0

### ISSUE THREAD

**Issue by blacktopol** [perliedman/leaflet-underneath#4]
I try use leaflet-underneath with Leaflet 1.0 and get errors

TypeError: this._tileLoaded is not a function
TypeError: this._addTilesFromCenterOut is not a function

_tileLoaded() function exist only in Leaflet 0.7

**Comment by perliedman** [comment]
Hm, it does indeed look like I haven't verified this with 1.0.0.

Sorry for giving the impression it is compatible with 1.0.0; I thought I had checked, but my mind must have slipped.

I'll try to fix 1.0.0 compatibility, but I can't promise when... help is of course very welcome.

**Comment by perliedman** [comment]
Finally fixed by 0bfc0ac2be942697f5fb724e4aa7ef3c6bc6bccd :tada:
